# Generated by Django 2.2.28 on 2024-11-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20241118_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrainement',
            name='type_entrainement',
        ),
        migrations.AddField(
            model_name='entrainement',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Billet',
        ),
    ]
