# Generated by Django 2.2.28 on 2024-11-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20241118_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrainement',
            name='type_entrainement',
            field=models.CharField(choices=[('Natation', 'Natation'), ('Course à pied', 'Course à pied'), ('Cyclisme', 'Cyclisme'), ('Repos', 'Repos')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
