# Generated by Django 2.2.28 on 2024-11-18 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_entrainement_type_entrainement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id_athlete', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('etat', models.CharField(choices=[('repos', 'Repos'), ('entraîné', 'Entraîné'), ('fatigué', 'Fatigué')], max_length=20)),
                ('discipline', models.CharField(choices=[('natation', 'Natation'), ('course', 'Course'), ('cyclisme', 'Cyclisme')], max_length=20)),
                ('equipe', models.CharField(max_length=20)),
                ('photo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id_equip', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('disponibilite', models.CharField(choices=[('libre', 'Libre'), ('occupé', 'Occupé')], max_length=20)),
                ('photo', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Entrainement',
        ),
        migrations.DeleteModel(
            name='Personne',
        ),
        migrations.AddField(
            model_name='athlete',
            name='lieu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Equipement'),
        ),
    ]
