# Generated by Django 2.2.28 on 2024-11-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20241118_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='equipe',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='photo',
        ),
        migrations.AlterField(
            model_name='athlete',
            name='discipline',
            field=models.CharField(choices=[('natation', 'Natation'), ('course', 'Course'), ('cyclisme', 'Cyclisme'), ('repos', 'repos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='etat',
            field=models.CharField(choices=[('reposé', 'reposéé'), ('fatigué', 'fatigué'), ('épuisé', 'épuisé'), ('entrainé', 'entrainé')], max_length=20),
        ),
    ]
