# Generated by Django 2.2.28 on 2024-11-18 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20241118_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id_character', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('etat', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('team', models.CharField(max_length=20)),
                ('photo', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='equipement',
            name='disponibilite',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Athlete',
        ),
        migrations.AddField(
            model_name='character',
            name='lieu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Equipement'),
        ),
    ]
