# Generated by Django 2.2.28 on 2024-11-18 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20241118_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='character',
            name='team',
        ),
        migrations.RemoveField(
            model_name='character',
            name='type',
        ),
    ]
