# Generated by Django 2.2.28 on 2024-11-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20241118_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='capacite_max',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='equipement',
            name='nombre_actuel',
            field=models.IntegerField(default=0),
        ),
    ]
